### PR TITLE
SubsystemObject: properly wrap the logger object with log methods

### PR DESCRIPTION
**Pull request by dawagner**
Plugins had access to a protected member that allowed them to log using:

    _logger.info() << "some log";

This is a design flaw because members shouldn't be exposed (either public or
protected). Instead, SubsystemObject now has two protected methods: info() and
warning() that wrap this _logger member, which is now private. Also, the code
required to log is nicer:

    info() << "some log";

Signed-off-by: David Wagner <david.wagner@intel.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/259%23issuecomment-144344850%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/259%23issuecomment-144344977%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/259%23issuecomment-144344850%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40OznOg%20%40krocard%20Please%20review%22%2C%20%22created_at%22%3A%20%222015-09-30T10%3A02%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%20so%20great%20%21%22%2C%20%22created_at%22%3A%20%222015-09-30T10%3A03%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/259#issuecomment-144344850'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> @OznOg @krocard Please review
- <a href='https://github.com/OznOg'></a> :+1:  so great !

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/259?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/259?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/259'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/259'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
@OznOg @krocard Please review

**Comment by OznOg** [comment]
:+1:  so great !

**Comment by dawagner** [comment]
Merged in the v3candidate branch

**Pull request closed without merging**
