### PR TITLE
Remove some traces inside ParameterMgr

### PR DESCRIPTION
**Pull request by miguelgaio**
Traces should be kept to minimum in query type methods as may result in
overwhelming outputs on the console, possibly hiding more important stuff.

Signed-off-by: Patrick Benavoli <patrick.benavoli@intel.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/193%23issuecomment-138926364%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/193%23issuecomment-138941010%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/193%23issuecomment-138926364%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40krocard%20%40cc6565%20%40OznOg%20%40dawagner%20%40louizo%22%2C%20%22created_at%22%3A%20%222015-09-09T14%3A26%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-09T15%3A08%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/dawagner%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/dawagner'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/193#issuecomment-138926364'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> @krocard @cc6565 @OznOg @dawagner @louizo

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/193?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/193?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/193?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/193'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/193'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by miguelgaio** [comment]
@krocard @cc6565 @OznOg @dawagner @louizo

**Comment by dawagner** [comment]
:shipit:

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
