### PR TITLE
Cmake transitive header inclusion

### PR DESCRIPTION
**Pull request by krocard**
Enhance cmake configuration by:
 - avoiding cach configuration duplication
 - lib now declare their public header
 - lib no longer need to explicitly include the include dir of used library
 - enhance catch error message

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146439816%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146473587%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146478690%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146478852%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146480600%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146544374%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/273%23issuecomment-146439816%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Resubmit%20%20of%20%23200%20on%20master%22%2C%20%22created_at%22%3A%20%222015-10-08T07%3A08%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A-1%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-08T09%3A38%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-08T09%3A55%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20feel%20free%20to%20merge%20anytime.%22%2C%20%22created_at%22%3A%20%222015-10-08T09%3A56%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%3Agun%3A%22%2C%20%22created_at%22%3A%20%222015-10-08T10%3A04%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-10-08T13%3A25%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/273#issuecomment-146439816'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> Resubmit  of #200 on master
- <a href='https://github.com/dawagner'></a> :-1:
- <a href='https://github.com/dawagner'></a> :shipit:
- <a href='https://github.com/dawagner'></a> @krocard feel free to merge anytime.
- <a href='https://github.com/dawagner'></a> :shipit::gun:

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/273?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/273?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/273?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/273'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/273'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
Resubmit  of #200 on master

**Comment by dawagner** [comment]
:-1:

**Comment by dawagner** [comment]
:shipit:

**Comment by dawagner** [comment]
@krocard feel free to merge anytime.

**Comment by dawagner** [comment]
:shipit::gun:

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
