### PR TITLE
Disable fix point test if no python bindings

### LINKED ISSUE #163: Can not run `make test` without python bindings
## How to reproduce
 - Disable the python bindings `-DBINDINGS_PYTHON=no`
 - run `make test`
`make test` fails complaining that the "fix point parameter" tests could not find the python bindings.

## Expected result
 - `make test` should success

## Propose fix
Disable the "fix point parameter tests" it if the python bindings are not compiled.

I submited a pull request: #116 but the fix did not work

### PR DESCRIPTION
**Pull request by dawagner**
The fix point parameter test can not run without python bindings.

Disable it if the python bindings are not compiled.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/176%23issuecomment-136798260%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/176%23issuecomment-136798747%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/176%23issuecomment-136799266%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/176%23issuecomment-136798260%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Reuse%20%23116.%20Fixes%20%23163.%22%2C%20%22created_at%22%3A%20%222015-09-01T17%3A06%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20please%20review.%22%2C%20%22created_at%22%3A%20%222015-09-01T17%3A08%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-01T17%3A10%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/176#issuecomment-136798260'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> Reuse #116. Fixes #163.
- <a href='https://github.com/dawagner'></a> @krocard please review.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/176?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/176?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/176?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/176'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/176'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
Reuse #116. Fixes #163.

**Comment by dawagner** [comment]
@krocard please review.

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
