### PR TITLE
Wconversion enabler

### PR DESCRIPTION
**Pull request by miguelgaio**
<a href='#crh-start'></a><a href='#crh-data-%7B%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/264?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/264'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/264'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
@krocard Please resubmit against master

**Comment by krocard** [comment]
@miguelgaio Please resubmit against `serialization_api` branch.

**Comment by krocard** [comment]
:+1: Resubmited on #272, removing resubmit label.

**Pull request closed without merging**
