### PR TITLE
[review] Update doxygen

### PR DESCRIPTION
**Pull request by dawagner**
update the Doxyfile with doxygen 1.8.9.1.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-171643351%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-171688474%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-171689094%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-171974893%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-172796204%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-172863949%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/335%23issuecomment-171643351%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40krocard%20%40tcahuzax%20please%20review.%22%2C%20%22created_at%22%3A%20%222016-01-14T13%3A23%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20BTW%20github%20doxygen%20has%20not%20been%20uploaded%20since%20v3.0%22%2C%20%22created_at%22%3A%20%222016-01-14T16%3A20%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20yes%20it%20has%3A%20http%3A//01org.github.io/parameter-framework/doc/annotated.html%20%28uploaded%20it%20yesterday%29%22%2C%20%22created_at%22%3A%20%222016-01-14T16%3A22%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20please%20review%20%28one%20commit%20added%20on%20top%20of%20the%20ones%20you%20already%20reviewed%29.%22%2C%20%22created_at%22%3A%20%222016-01-15T14%3A29%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20ping.%22%2C%20%22created_at%22%3A%20%222016-01-19T09%3A52%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222016-01-19T14%3A08%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/335#issuecomment-171643351'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> @krocard @tcahuzax please review.
- <a href='https://github.com/krocard'></a> :+1: BTW github doxygen has not been uploaded since v3.0
- <a href='https://github.com/dawagner'></a> @krocard yes it has: http://01org.github.io/parameter-framework/doc/annotated.html (uploaded it yesterday)
- <a href='https://github.com/dawagner'></a> @krocard please review (one commit added on top of the ones you already reviewed).
- <a href='https://github.com/dawagner'></a> @krocard ping.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/335?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/335?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/335?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/335'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/335'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
@krocard @tcahuzax please review.

**Comment by krocard** [comment]
:+1: BTW github doxygen has not been uploaded since v3.0

**Comment by dawagner** [comment]
@krocard yes it has: http://01org.github.io/parameter-framework/doc/annotated.html (uploaded it yesterday)

**Comment by dawagner** [comment]
@krocard please review (one commit added on top of the ones you already reviewed.

**Comment by dawagner** [comment]
@krocard ping.

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
