### PR TITLE
[review] Element handle

### PR DESCRIPTION
**Pull request by krocard**
CElementHandle can be used by applications to directly control an element part of the parameter tree. CElementHandle objects can be created by calling the platform connector class new createElementHandle() functionality.

Element handle objects are owned by the application so it's its responsibility to destroy them through a "delete" operation.

The following functionalities are available in CElementHandle class:
 - getting element's name
 - getting element's path in parameter hierarchy tree
 - getting element's memory size in bytes
 - determining if element is rogue
 - getting the structure of the element (expanded version of the structure)
 - getting/setting the element's settings in XML format
 - getting/setting the element's settings in binary format

Notes:
 - setting the element's settings in binary shall be done cautiously: no check is made as to the data integrity, meaning the operation could result in inconsistent parameter states where some parameter values are out of range or invalid wrt their type
 - setting the element's settings will fail if the element is not rogue (belong to a domain or one of its descendent does)
 - if a tuning application has set the auto sync mode to off, the changes applied through CElementHandle will be forward-synchronized when the auto sync mode is set back to on or when the "sync" remote command is executed.
 - when the tuning mode is on, calls to setAsXML() and setAsBytes() will fail silently (do nothing but return success)
 - The handle is not tested !
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-151878045%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-151892347%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-152539656%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-153413433%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-153413482%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/300%23issuecomment-151878045%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A-1%3A%20review%20done.%22%2C%20%22created_at%22%3A%20%222015-10-28T15%3A16%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A-1%3A%20reviews%20done%22%2C%20%22created_at%22%3A%20%222015-10-28T15%3A59%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A-1%3A%20review%20done%22%2C%20%22created_at%22%3A%20%222015-10-30T14%3A24%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22main%20change%20is%3A%20https%3A//github.com/krocard/parameter-framework/commit/0f29ce1957d994e2510e10092549fc20c8243fc5%22%2C%20%22created_at%22%3A%20%222015-11-03T16%3A48%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-03T16%3A48%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/300#issuecomment-151878045'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> :-1: review done.
- <a href='https://github.com/tcahuzax'></a> :-1: reviews done
- <a href='https://github.com/dawagner'></a> :-1: review done
- <a href='https://github.com/krocard'></a> main change is: https://github.com/krocard/parameter-framework/commit/0f29ce1957d994e2510e10092549fc20c8243fc5

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/300?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/300?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/300?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/300'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/300'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
:-1: review done.

**Comment by tcahuzax** [comment]
:-1: reviews done

**Comment by dawagner** [comment]
:-1: review done

**Comment by krocard** [comment]
main change is: https://github.com/krocard/parameter-framework/commit/0f29ce1957d994e2510e10092549fc20c8243fc5

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
