### PR TITLE
Replace CUtility::toString with C++11's std::to_string

### PR DESCRIPTION
**Pull request by dawagner**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/219%23issuecomment-139555763%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/219%23issuecomment-139569159%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/219%23issuecomment-139586927%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/219%23issuecomment-139994261%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/219%23issuecomment-139555763%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-11T14%3A03%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-11T15%3A02%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dawagner%20please%20rebase%22%2C%20%22created_at%22%3A%20%222015-09-11T16%3A06%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-14T08%3A17%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/219#issuecomment-139555763'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1:
- <a href='https://github.com/miguelgaio'></a> :+1:
- <a href='https://github.com/krocard'></a> @dawagner please rebase

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/219?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/219?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/219'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/219'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1:

**Comment by miguelgaio** [comment]
:+1:

**Comment by krocard** [comment]
@dawagner please rebase

**Comment by OznOg** [comment]
:+1:

**Pull request merged**
