### PR TITLE
Appveyor: activate the compilation of parameter and remote-processor

### PR DESCRIPTION
**Pull request by dawagner**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/223%23issuecomment-139607933%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/223%23issuecomment-140316033%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/223%23issuecomment-140324678%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/223%23issuecomment-139607933%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Need%20%23218%20before.%22%2C%20%22created_at%22%3A%20%222015-09-11T17%3A32%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20merged%20%23229%20that%20should%20remove%20the%20%60strings.h%60%20inclusion%20failure.%20So%20I%20retrigered%20a%20appveyor%20build.%22%2C%20%22created_at%22%3A%20%222015-09-15T08%3A11%3A47Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22Build%20succeeded.%20Merging.%22%2C%20%22created_at%22%3A%20%222015-09-15T08%3A45%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/223#issuecomment-139607933'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> Need #218 before.
- <a href='https://github.com/krocard'></a> I merged #229 that should remove the `strings.h` inclusion failure. So I retrigered a appveyor build.
- <a href='https://github.com/krocard'></a> Build succeeded. Merging.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/223?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/223?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/223'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/223'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
Need #218 before.

**Comment by krocard** [comment]
I merged #229 that should remove the `strings.h` inclusion failure. So I retrigered a appveyor build.

**Comment by krocard** [comment]
Build succeeded. Merging.

**Pull request merged**
