### PR TITLE
Remove CXX compiler verbose flag for swig binding

### PR DESCRIPTION
**Pull request by krocard**
When compiling swig generated files, the CXX compiler
flag list included -v. This leaded to unnecessary log
output during compilation. =>_Remove the flag.

Some cmake command were in upper case.

### CODE REVIEW

**Comment by Makohoek** [comment]
:+1:

**Comment by dawagner** [comment]
:-1: It breaks:

    swig error : Unrecognized option -Wall -Werror

see http://stackoverflow.com/questions/17043088/cmake-build-calling-swig-with-multiple-arguments

The correct version would be:

    SET_PROPERTY(SOURCE pfw.i PROPERTY SWIG_FLAGS "-Wall" "-Werror")

and the current makefile is wrong too.

**Comment by krocard** [comment]
:-1:

**Comment by krocard** [comment]
:+1:

**Pull request merged**
