### PR TITLE
Switch Travis build back to containor mode

### PR DESCRIPTION
**Pull request by krocard**
travis was reverted to it's legacy mode, building with a vm instead of
a docker based container.

This change was made to be able to use sudo to install a recent cmake
package.

Nevertheless it had several disadvantages:
 - travis.yml is less readable
 - build is slower (not that much though)
 - recipe require sudo

After double checking, a few ppa witelisted for the container
contained a cmake recent backport. So using docker travis mode
is possible.

 - Revert to container build as this is the preferred and recommended travis build mode.
 - Install a more version cmake with a whitelisted ppa backport
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140081933%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140099363%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140099537%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140110931%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140120806%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/227%23issuecomment-140081933%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22after%20%23218%20%3F%22%2C%20%22created_at%22%3A%20%222015-09-14T13%3A52%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40miguelgaio%20%40OznOg%20Please%20review.%20Ignore%20last%20patch%20%28%5C%22Add%20support%20for%20Export/Import%20symbols%20API%5C%22%29%20as%20it%20is%20a%20travis%20test%20to%20check%20that%20%23218%20is%20not%20broken.%22%2C%20%22created_at%22%3A%20%222015-09-14T14%3A31%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%23218%20is%20not%20brocken%20by%20this%20pull%20request%20as%20proven%20by%20https%3A//travis-ci.org/01org/parameter-framework/builds/80249749%22%2C%20%22created_at%22%3A%20%222015-09-14T14%3A31%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-14T15%3A08%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-14T15%3A45%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/227#issuecomment-140081933'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> after #218 ?
- <a href='https://github.com/krocard'></a> :+1: @dawagner @miguelgaio @OznOg Please review. Ignore last patch ("Add support for Export/Import symbols API") as it is a travis test to check that #218 is not broken.
- <a href='https://github.com/krocard'></a> #218 is not brocken by this pull request as proven by https://travis-ci.org/01org/parameter-framework/builds/80249749

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/227?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/227?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/227'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/227'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by miguelgaio** [comment]
after #218 ?

**Comment by krocard** [comment]
:+1: @dawagner @miguelgaio @OznOg Please review. Ignore last patch ("Add support for Export/Import symbols API") as it is a travis test to check that #218 is not broken.

**Comment by krocard** [comment]
#218 is not brocken by this pull request as proven by https://travis-ci.org/01org/parameter-framework/builds/80249749

**Comment by krocard** [comment]
:+1:

**Comment by miguelgaio** [comment]
:+1:

**Pull request merged**
