### PR TITLE
Avoid confusing command line in readme

### PR DESCRIPTION
**Pull request by louizo**
Some people are confused with the example path that
ends with "/source", by default the path is ending
with parameter-framework.

to avoid any confusion, change the example path by
parameter-framework in the README.md document.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/161%23issuecomment-132221708%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/161%23issuecomment-132235454%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/161%23issuecomment-132239124%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/161%23issuecomment-132221708%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40dawagner%20%40krocard%20%40OznOg%20please%20review%20%3A%29%22%2C%20%22created_at%22%3A%20%222015-08-18T14%3A09%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12612524%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/louizo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-08-18T14%3A41%3A38Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-08-18T14%3A54%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/161#issuecomment-132221708'>General Comment</a></b>
- <a href='https://github.com/louizo'></a> @dawagner @krocard @OznOg please review :)

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/161?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/161?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/161?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/161'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/161'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by louizo** [comment]
@dawagner @krocard @OznOg please review :)

**Comment by krocard** [comment]
:shipit:

**Comment by OznOg** [comment]
:+1:

**Pull request merged**
