### PR TITLE
Rework remote server

### PR DESCRIPTION
**Pull request by cc6565**
Split the RemoteProcessorServer into a server object (in charge of listening and processing messages from a pipe) and background server in charge of threading the server object.
It allows the test platform to bypass thread creation and avoid useless synchronization. 

It also changes the way parameter library is linking with remote processor: this library is not opened through a dlopen any more but parameter links with dynamic remote processor library instead.

Creating or not the remote processor server depends now only of the tuning allowed flag set within the configuration file of the Parameter Framework.

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/185%23issuecomment-138493486%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/185%23issuecomment-138493861%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/185%23issuecomment-138494720%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/185%23issuecomment-138493486%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40cc6565%20Please%20fix%20all%20the%20commit%20messages.%22%2C%20%22created_at%22%3A%20%222015-09-08T09%3A23%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40cc6565%20%40OznOg%20Please%20provide%20a%20more%20complete%20Pull%20Request%20message%20mentioning%20the%20new%20separation%20of%20responsibilities.%22%2C%20%22created_at%22%3A%20%222015-09-08T09%3A25%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22Also%2C%20in%20most%20commit%20message%20headlines%2C%20it%20is%20impossible%20to%20tell%20which%20component%20is%20changed.%5Cr%5Cn%5Cr%5Cne.g.%5Cr%5Cn%5Cr%5Cn%20%20%20%20move%20commands%20into%20where%20it%20belongs%20%5Cr%5Cn%5Cr%5Cnbecomes%5Cr%5Cn%5Cr%5Cn%20%20%20%20test-platform%3A%20move%20command%20definitions%20to%20the%20thread%20function%22%2C%20%22created_at%22%3A%20%222015-09-08T09%3A28%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/185#issuecomment-138493486'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> @cc6565 Please fix all the commit messages.
- <a href='https://github.com/dawagner'></a> @cc6565 @OznOg Please provide a more complete Pull Request message mentioning the new separation of responsibilities.
- <a href='https://github.com/dawagner'></a> Also, in most commit message headlines, it is impossible to tell which component is changed.
e.g.
move commands into where it belongs
becomes
test-platform: move command definitions to the thread function

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/185?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/185?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/185'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/185'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
@cc6565 Please fix all the commit messages.

**Comment by dawagner** [comment]
@cc6565 @OznOg Please provide a more complete Pull Request message mentioning the new separation of responsibilities.

**Comment by dawagner** [comment]
Also, in most commit message headlines, it is impossible to tell which component is changed.

e.g.

    move commands into where it belongs 

becomes

    test-platform: move command definitions to the thread function

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
