### PR TITLE
Xml generation fixes and tests

### PR DESCRIPTION
**Pull request by dawagner**
- change how schema are found and XML files validated
- fix the XML generation script
- add XML generation tests

@tcahuzax please review.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/320%23issuecomment-164798249%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/320%23issuecomment-165412138%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/320%23issuecomment-165468107%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/320%23issuecomment-165493856%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/320%23issuecomment-164798249%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22coverage%20increased%20by%20%2B0.8%25%22%2C%20%22created_at%22%3A%20%222015-12-15T15%3A28%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A-1%3A%22%2C%20%22created_at%22%3A%20%222015-12-17T10%3A29%3A30Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tcahuzax%20I%20have%20addressed%20your%20comments.%22%2C%20%22created_at%22%3A%20%222015-12-17T14%3A37%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-12-17T16%3A00%3A17Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/tcahuzax%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/tcahuzax'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/320#issuecomment-164798249'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> coverage increased by +0.8%
- <a href='https://github.com/tcahuzax'></a> :-1:
- <a href='https://github.com/dawagner'></a> @tcahuzax I have addressed your comments.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/320?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/320?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/320?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/320'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
coverage increased by +0.8%

**Comment by tcahuzax** [comment]
:-1:

**Comment by dawagner** [comment]
@tcahuzax I have addressed your comments.

**Comment by tcahuzax** [comment]
:shipit:

**Pull request merged**
