### PR TITLE
[review] Simplify empty ctors and dtors

### PR DESCRIPTION
**Pull request by dawagner**
Follows #296. to be merged after.

Let the compiler generate some trivial code, so that we don't need to explicitly write it.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/298%23issuecomment-152549578%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/298%23issuecomment-152969746%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/298%23issuecomment-152970192%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/298%23issuecomment-152549578%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40tcahuzax%20%40krocard%20please%20review%20%28only%20the%20last%203%20commits%3A%20the%20first%20two%20are%20part%20of%20%23296%29%22%2C%20%22created_at%22%3A%20%222015-10-30T15%3A04%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-02T09%3A33%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-02T09%3A35%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/298#issuecomment-152549578'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> @tcahuzax @krocard please review (only the last 3 commits: the first two are part of #296)

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/298?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/298?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/298?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/298'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/298'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
@tcahuzax @krocard please review (only the last 3 commits: the first two are part of #296)

**Comment by tcahuzax** [comment]
:+1:

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
