### PR TITLE
Miscellaneous fixes for windows

### PR DESCRIPTION
**Pull request by krocard**
Several fix for windows compilation
 - Add windows specific flags for skeleton subsystem
 - Remove the need for a semaphore in test-platform -> use a future&promise
 - Correct a unnecessary cast that was loosing precision
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/172%23issuecomment-135723057%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/172%23issuecomment-135723311%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/172%23issuecomment-135726923%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/172%23issuecomment-135723057%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40OznOg%20%40dawagner%20please%20review%22%2C%20%22created_at%22%3A%20%222015-08-28T09%3A51%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-08-28T09%3A53%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-08-28T10%3A10%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/172#issuecomment-135723057'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> @OznOg @dawagner please review

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/172?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/172?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/172'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/172'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
@OznOg @dawagner please review

**Comment by krocard** [comment]
:+1:

**Comment by OznOg** [comment]
:+1:

**Pull request merged**
