### PR TITLE
[review] Add "array" capability to Components

### PR DESCRIPTION
**Pull request by dawagner**
Numerical parameters as well as ParameterBlocks can have an "ArrayLength" attribute that instantiate as many identical parameters or parameter blocks.

This is now also possible for Component instances (not types).

The Semantic of this feature is very unclear, even now... use with caution.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/305%23issuecomment-158081519%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/305%23issuecomment-158094690%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/305%23issuecomment-158386857%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/305%23issuecomment-158081519%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40tcahuzax%20%40krocard%20please%20review.%22%2C%20%22created_at%22%3A%20%222015-11-19T14%3A58%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-19T15%3A43%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A-1%3A%22%2C%20%22created_at%22%3A%20%222015-11-20T12%3A38%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/305#issuecomment-158081519'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> @tcahuzax @krocard please review.
- <a href='https://github.com/krocard'></a> :+1:
- <a href='https://github.com/tcahuzax'></a> :-1:

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/305?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/305?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/305'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/305'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
@tcahuzax @krocard please review.

**Comment by krocard** [comment]
:+1:

**Comment by tcahuzax** [comment]
:-1:

**Pull request merged**
