### PR TITLE
Encapsulate subsystem blackboard access

### PR DESCRIPTION
**Pull request by krocard**
Avoid subsystem direct access to the blackboard buffer.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/192%23issuecomment-138921976%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/192%23issuecomment-138933093%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/192%23issuecomment-139228942%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/192%23issuecomment-138921976%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40OznOg%20%40dawagner%22%2C%20%22created_at%22%3A%20%222015-09-09T14%3A11%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22ok%20for%20me%20once%20%5C%22...Buff%5C%22%20methods%20are%20renamed%20to%20%5C%22...Buffer%5C%22.%22%2C%20%22created_at%22%3A%20%222015-09-09T14%3A43%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40OznOg%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-10T13%3A04%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/192#issuecomment-138921976'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @dawagner @OznOg @dawagner
- <a href='https://github.com/dawagner'></a> ok for me once "...Buff" methods are renamed to "...Buffer".
- <a href='https://github.com/krocard'></a> @OznOg please review

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/192?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/192?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/192'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/192'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1: @dawagner @OznOg @dawagner

**Comment by dawagner** [comment]
ok for me once "...Buff" methods are renamed to "...Buffer".

**Comment by krocard** [comment]
@OznOg please review

**Pull request merged**
