### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by krocard**
- fix a warning in release were parameters were unused
- fix a warning in recent compiler about auto_ptr depreciation
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-156851416%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-156958993%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-156975340%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-157099872%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-157374514%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/315%23issuecomment-156851416%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40tcahuzax%20please%20review%22%2C%20%22created_at%22%3A%20%222015-11-15T20%3A37%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-16T08%3A57%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40krocard%20please%20also%20consider%20cherry-picking%20https%3A//github.com/dawagner/parameter-framework/commit/fix-unused-variable%22%2C%20%22created_at%22%3A%20%222015-11-16T09%3A57%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40dawagner%20%20done%20%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-16T17%3A06%3A02Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-17T13%3A48%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/tcahuzax%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/tcahuzax'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/315#issuecomment-156851416'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @dawagner @tcahuzax please review
- <a href='https://github.com/dawagner'></a> :+1:
- <a href='https://github.com/dawagner'></a> @krocard please also consider cherry-picking https://github.com/dawagner/parameter-framework/commit/fix-unused-variable
- <a href='https://github.com/krocard'></a> @dawagner  done :+1:

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/315?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/315?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/315?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/315'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by krocard** [comment]
:+1: @dawagner @tcahuzax please review

**Comment by dawagner** [comment]
:+1:

**Comment by dawagner** [comment]
@krocard please also consider cherry-picking https://github.com/dawagner/parameter-framework/commit/fix-unused-variable

**Comment by krocard** [comment]
@dawagner  done

**Comment by tcahuzax** [comment]
:shipit:

**Pull request merged**
