### PR TITLE
Schemas

### PR DESCRIPTION
**Pull request by mgaio**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/267%23issuecomment-145510658%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/267%23issuecomment-177883360%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/267%23issuecomment-177883976%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/267%23issuecomment-177884086%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/267%23issuecomment-145510658%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40dawagner%20%40krocard%20%40OznOg%20%40cc6565%20please%20review%22%2C%20%22created_at%22%3A%20%222015-10-05T12%3A22%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40mgaio%20Is%20this%20PR%20still%20relevant%20%3F%22%2C%20%22created_at%22%3A%20%222016-02-01T09%3A54%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22Yes.%20%22%2C%20%22created_at%22%3A%20%222016-02-01T09%3A56%3A11Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22yes%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222016-02-01T09%3A56%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/mgaio%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/267#issuecomment-145510658'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> @dawagner @krocard @OznOg @cc6565 please review
- <a href='https://github.com/krocard'></a> @mgaio Is this PR still relevant ?
- <a href='https://github.com/mgaio'></a> Yes.
- <a href='https://github.com/mgaio'></a> yes

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/267?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/267?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/267'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/267'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by miguelgaio** [comment]
@dawagner @krocard @OznOg @cc6565 please review

**Comment by krocard** [comment]
@mgaio Is this PR still relevant ?

**Comment by mgaio** [comment]
Yes.

**Comment by mgaio** [comment]
yes

**Pull request closed without merging**
