### PR TITLE
Warn when loading a subsystem in virtual mode

### PR DESCRIPTION
**Pull request by krocard**
Starting a subsystem in virtual mode is often a temporary hack in order to start the parameter framework with a buggy subsystem.

This modification although useful in some case, may lead to hard to debug bug if the user is not aware of the virtual state.

Notify the user by warning when a subsystem in loaded in virtual.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/271%23issuecomment-146196593%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/271%23issuecomment-148427201%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/271%23issuecomment-148430919%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/271%23issuecomment-148431671%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/271%23issuecomment-146196593%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40dawagner%20please%20review%22%2C%20%22created_at%22%3A%20%222015-10-07T13%3A29%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tcahuzax%20Please%20review%22%2C%20%22created_at%22%3A%20%222015-10-15T15%3A40%3A10Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40dawagner%20%20Please%20approve%22%2C%20%22created_at%22%3A%20%222015-10-15T15%3A54%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-10-15T15%3A56%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/dawagner%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/dawagner'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/271#issuecomment-146196593'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> @dawagner please review
- <a href='https://github.com/krocard'></a> @tcahuzax Please review
- <a href='https://github.com/krocard'></a> :+1: @dawagner @dawagner  Please approve

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/271?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/271?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/271?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/271'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/271'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
@dawagner please review

**Comment by krocard** [comment]
@tcahuzax Please review

**Comment by krocard** [comment]
:+1: @dawagner @dawagner  Please approve

**Comment by dawagner** [comment]
:shipit:

**Pull request merged**
