### PR TITLE
Test platform: Remove unused strings.h inclusion

### PR DESCRIPTION
**Pull request by krocard**
The header was not used and not cross platform =>Remove it.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/229%23issuecomment-140137827%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/229%23issuecomment-140315593%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/229%23issuecomment-140315701%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/229%23issuecomment-140137827%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40OznOg%22%2C%20%22created_at%22%3A%20%222015-09-14T16%3A37%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-15T08%3A09%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9692938%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cc6565%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-15T08%3A09%3A42Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/cc6565%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9692938%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a><a href='https://github.com/cc6565'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/229#issuecomment-140137827'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @dawagner @OznOg

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/229?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/229?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/229?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/229'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/229'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1: @dawagner @OznOg

**Comment by cc6565** [comment]
:shipit:

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
