### PR TITLE
Symbol export: add missing CFormattedSubsystemObject class

### PR DESCRIPTION
**Pull request by dawagner**
We forgot to export this class, which is intended to be used by plugins.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/242%23issuecomment-141523977%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/242%23issuecomment-141524205%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/242%23issuecomment-141524562%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/242%23issuecomment-141523977%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-18T18%3A16%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40OznOg%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-18T18%3A17%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-18T18%3A18%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/242#issuecomment-141523977'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1:
- <a href='https://github.com/dawagner'></a> @OznOg please review

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/242?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/242?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/242?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/242'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/242'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1:

**Comment by dawagner** [comment]
@OznOg please review

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
