### PR TITLE
Add complex edd test

### PR DESCRIPTION
**Pull request by krocard**
- Test complex XML generation from EDD features (nested).
 - XML generation from EDD test was not detecting failure.
 - XML generation from EDD had a bug that made impossible to use the sequence aware domain feature
 - Fix various error message typos.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/331%23issuecomment-170575725%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/331%23issuecomment-170575861%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/331%23issuecomment-170620286%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/331%23issuecomment-170575725%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40tcahuzax%20please%20review%22%2C%20%22created_at%22%3A%20%222016-01-11T14%3A48%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20build%20failed%20because%20of%20clang-format%20%3A-1%3A%20%22%2C%20%22created_at%22%3A%20%222016-01-11T14%3A49%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%2B%20please%20review%20%23329%20and%20merge%20if%20ok.%22%2C%20%22created_at%22%3A%20%222016-01-11T17%3A07%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/dawagner%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/dawagner'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/331#issuecomment-170575725'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @tcahuzax please review
- <a href='https://github.com/krocard'></a> The build failed because of clang-format :-1:
- <a href='https://github.com/dawagner'></a> :shipit: + please review #329 and merge if ok.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/331?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/331?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/331?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/331'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/331'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1: @tcahuzax please review

**Comment by krocard** [comment]
The build failed because of clang-format :-1:

**Comment by dawagner** [comment]
:shipit: + please review #329 and merge if ok.

**Pull request merged**
