### PR TITLE
Fixed the low value param

### PR DESCRIPTION
**Pull request by miguelgaio**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/190%23issuecomment-138893953%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/190%23issuecomment-138894449%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/190%23issuecomment-138907814%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/190%23issuecomment-138910516%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/190%23issuecomment-138893953%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40krocard%20%40cc6565%20%40OznOg%20%40dawagner%20%40louizo%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-09T12%3A26%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-09T12%3A28%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%2C%20%7B%22body%22%3A%20%22Remove%20change-Id%20from%20the%20commit%20message%20please.%20%22%2C%20%22created_at%22%3A%20%222015-09-09T13%3A23%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-09-09T13%3A34%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/190#issuecomment-138893953'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> @krocard @cc6565 @OznOg @dawagner @louizo please review
- <a href='https://github.com/OznOg'></a> :+1:
- <a href='https://github.com/krocard'></a> Remove change-Id from the commit message please.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/190?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/190?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/190'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/190'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by miguelgaio** [comment]
@krocard @cc6565 @OznOg @dawagner @louizo please review

**Comment by OznOg** [comment]
:+1:

**Comment by krocard** [comment]
Remove change-Id from the commit message please.

**Comment by miguelgaio** [comment]
:+1:

**Pull request merged**
