### PR TITLE
appveyor.yml: Use *debug* libxml2 for debug build

### PR DESCRIPTION
**Pull request by krocard**
The previous patch wrongly factorised the path to libxml2 for both release and debug although they are different.

Mixing debug and release libs is not recommended and therefore, the two different path are restored.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/233%23issuecomment-140478736%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/233%23issuecomment-140729071%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/233%23issuecomment-140730009%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/233%23issuecomment-140478736%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40OznOg%20Please%20review%20%26%20merge.%22%2C%20%22created_at%22%3A%20%222015-09-15T17%3A43%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40louizo%20%40miguelgaio%20%40cc6565%20Please%20review.%20Really%20anyone%20please%20review.%22%2C%20%22created_at%22%3A%20%222015-09-16T12%3A36%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-16T12%3A41%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/233#issuecomment-140478736'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @dawagner @OznOg Please review & merge.
- <a href='https://github.com/krocard'></a> @louizo @miguelgaio @cc6565 Please review. Really anyone please review.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/233?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/233?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/233'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/233'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
:+1: @dawagner @OznOg Please review & merge.

**Comment by krocard** [comment]
@louizo @miguelgaio @cc6565 Please review. Really anyone please review.

**Comment by miguelgaio** [comment]
:+1:

**Pull request merged**
