### PR TITLE
[review] Enhance export error detection and message in xml export

### PR DESCRIPTION
**Pull request by krocard**
Enable stream exception and use close explicitly the stream to detect
flush error and have nice error messages.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-156508011%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-156508759%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-156957936%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-156986126%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-157372469%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/312%23issuecomment-156508011%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20is%20a%20side%20patch%20of%20an%20old%20dropped%20pull%20request%20that%20can%20still%20be%20merged.%22%2C%20%22created_at%22%3A%20%222015-11-13T18%3A20%3A58Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%40dawagner%20%40tcahuzax%20please%20review%22%2C%20%22created_at%22%3A%20%222015-11-13T18%3A23%3A43Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-11-16T08%3A50%3A13Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-16T10%3A41%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-11-17T13%3A38%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tcahuzax%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/dawagner%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/tcahuzax%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11178583%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/dawagner'></a><a href='https://github.com/krocard'></a><a href='https://github.com/tcahuzax'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/312#issuecomment-156508011'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> This is a side patch of an old dropped pull request that can still be merged.
- <a href='https://github.com/krocard'></a> :+1: @dawagner @tcahuzax please review

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/312?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/312?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/312?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/312'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/312'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by krocard** [comment]
This is a side patch of an old droped pull request that can still be merged.

**Comment by krocard** [comment]
:+1: @dawagner @tcahuzax please review

**Comment by dawagner** [comment]
:shipit:

**Comment by krocard** [comment]
:shipit:

**Comment by tcahuzax** [comment]
:shipit:

**Pull request merged**
