### PR TITLE
Remove binary settings import/export feature

### PR DESCRIPTION
**Pull request by dawagner**
Nobody used it, it wasn't maintained and wasn't effectively filling any need.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142009538%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142032107%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142050239%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142050336%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142324484%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/244%23issuecomment-142009538%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-21T15%3A06%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-21T16%3A18%3A14Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9692938%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/cc6565%22%7D%7D%2C%20%7B%22body%22%3A%20%22update%3A%20remove%20dead%20code%20resulting%20from%20the%20removal%20of%20binary%20settings.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A29%3A56Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40OznOg%20%40krocard%20please%20review.%22%2C%20%22created_at%22%3A%20%222015-09-21T17%3A30%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-09-22T15%3A30%3A20Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/820313%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/OznOg%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/cc6565%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9692938%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/cc6565'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/244#issuecomment-142009538'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> :+1:
- <a href='https://github.com/cc6565'></a> :shipit:
- <a href='https://github.com/dawagner'></a> update: remove dead code resulting from the removal of binary settings.
- <a href='https://github.com/dawagner'></a> @OznOg @krocard please review.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/244?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/244?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/244?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/244'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/244'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by miguelgaio** [comment]
:+1:

**Comment by cc6565** [comment]
:shipit:

**Comment by dawagner** [comment]
update: remove dead code resulting from the removal of binary settings.

**Comment by dawagner** [comment]
@OznOg @krocard please review.

**Comment by OznOg** [comment]
:+1:

**Comment by krocard** [comment]
:shipit:

**Pull request merged**
