### PR TITLE
Remove android.mk

### PR DESCRIPTION
**Pull request by miguelgaio**
Android.mk are parts of Android integration.
Thus, they shoud not be present on master.

Signed-off-by: Miguel Gaio <miguel.gaio@intel.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141113496%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141122594%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141123722%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141136631%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141916263%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141916648%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141916987%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141950839%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141967098%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/237%23issuecomment-141113496%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40OznOg%20%40krocard%20%40dawagner%20%40cc6565%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-17T14%3A58%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22All%3A%20should%20we%20keep%20or%20remove%20%60support/android/build_pfw_settings.mk%60%20%3F%22%2C%20%22created_at%22%3A%20%222015-09-17T15%3A29%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22OK%20to%20remove%22%2C%20%22created_at%22%3A%20%222015-09-17T15%3A32%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20have%20a%20doubt%20because%20it%20is%20non-trivial.%20Maybe%20we%20should%20keep%20this%20in%20an%20integration%20documentation%20%3F%22%2C%20%22created_at%22%3A%20%222015-09-17T16%3A14%3A52Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-21T08%3A59%3A45Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22Approved%20but%20need%20to%20check%20something%20before%20I%20merge.%22%2C%20%22created_at%22%3A%20%222015-09-21T09%3A00%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40scentelles%20Please%20review.%22%2C%20%22created_at%22%3A%20%222015-09-21T09%3A01%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22While%20I%20agree%20with%20the%20pull%20request%2C%20I%20do%20not%20know%20if%20it%20is%20wise%20to%20remove%20all%20android.mk%20as%20we%20need%20to%20support%20android%20for%20the%20end%20of%20the%20month.%20What%20do%20you%20propose%20as%20alternative%20repository%20for%20the%20android%20makefiles%20%3F%22%2C%20%22created_at%22%3A%20%222015-09-21T11%3A53%3A39Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22Informally%20approved%20by%20%40scentelles.%20I%27m%20merging%20it.%22%2C%20%22created_at%22%3A%20%222015-09-21T12%3A59%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/dawagner%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/dawagner'></a>

- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/237#issuecomment-141113496'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> @OznOg @krocard @dawagner @cc6565 please review
- <a href='https://github.com/dawagner'></a> All: should we keep or remove `support/android/build_pfw_settings.mk` ?
- <a href='https://github.com/miguelgaio'></a> OK to remove
- <a href='https://github.com/dawagner'></a> I have a doubt because it is non-trivial. Maybe we should keep this in an integration documentation ?
- <a href='https://github.com/dawagner'></a> :shipit:
- <a href='https://github.com/dawagner'></a> Approved but need to check something before I merge.
- <a href='https://github.com/dawagner'></a> @scentelles Please review.
- <a href='https://github.com/krocard'></a> While I agree with the pull request, I do not know if it is wise to remove all android.mk as we need to support android for the end of the month. What do you propose as alternative repository for the android makefiles ?
- <a href='https://github.com/dawagner'></a> Informally approved by @scentelles. I'm merging it.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/237?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/237?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/237?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/237'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by miguelgaio** [comment]
@OznOg @krocard @dawagner @cc6565 please review

**Comment by miguelgaio** [comment]
@OznOg @krocard @dawagner @cc6565 please review

**Comment by dawagner** [comment]
All: should we keep or remove `support/android/build_pfw_settings.mk` ?

**Comment by miguelgaio** [comment]
OK to remove

**Comment by dawagner** [comment]
I have a doubt because it is non-trivial. Maybe we should keep this in an integration documentation ?

**Comment by dawagner** [comment]
:shipit:

**Comment by dawagner** [comment]
Approved but need to check something before I merge.

**Comment by dawagner** [comment]
@scentelles Please review.

**Comment by krocard** [comment]
While I agree with the pull request, I do not know if it is wise to remove all android.mk as we need to support android for the end of the month. What do you propose as alternative repository for the android makefiles ?

**Comment by dawagner** [comment]
Informally approved by @scentelles. I'm merging it.

**Pull request merged**
