### PR TITLE
Test skeleton plugin

### PR DESCRIPTION
**Pull request by dawagner**
Export its entry point and add a smoke test.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/252%23issuecomment-143732482%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/252%23issuecomment-144073737%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/252%23issuecomment-144111773%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/252%23issuecomment-144112924%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/252%23issuecomment-143732482%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Need%20%23255%20before%20merging.%22%2C%20%22created_at%22%3A%20%222015-09-28T12%3A44%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22Contains%20%23255%20%28which%20is%20only%20the%20%5C%22rework%20the%20plugin%20entry-point%20api%5C%22%20commit%29.%22%2C%20%22created_at%22%3A%20%222015-09-29T14%3A14%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22Closed%20because%20of%20miss%20click.%22%2C%20%22created_at%22%3A%20%222015-09-29T16%3A28%3A07Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-09-29T16%3A33%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/252#issuecomment-143732482'>General Comment</a></b>
- <a href='https://github.com/dawagner'></a> Need #255 before merging.
- <a href='https://github.com/dawagner'></a> Contains #255 (which is only the "rework the plugin entry-point api" commit).
- <a href='https://github.com/krocard'></a> Closed because of miss click.

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/252?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/252?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/252?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/252'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by dawagner** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/01org/parameter-framework/pull/252'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by dawagner** [comment]
Need some fixes that are being made by @krocard before this works on Windows.

**Comment by dawagner** [comment]
Need #255 before merging.

**Comment by dawagner** [comment]
Contains #255 (which is only the "rework the plugin entry-point api" commit).

**Comment by krocard** [comment]
Closed because of miss click.

**Comment by krocard** [comment]
:shipit:

**Comment by dawagner** [comment]
Merged in the v3candidate branch

**Pull request closed without merging**
