### PR TITLE
Disable fix point parameter test with python bindings

### PR DESCRIPTION
**Pull request by krocard**
The fix point parameter test can not run without python bindings.

Disable it if the python bindings are not compiled.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-103846117%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-103868473%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-103877778%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-103901843%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-132262048%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/116%23issuecomment-103846117%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3A%2B1%3A%20%40OznOg%20%40dawagner%20%22%2C%20%22created_at%22%3A%20%222015-05-20T11%3A12%3A16Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cn%5B%21%5BCoverage%20Status%5D%28https%3A//coveralls.io/builds/2606986/badge%29%5D%28https%3A//coveralls.io/builds/2606986%29%5Cn%5CnCoverage%20decreased%20%28-0.33%25%29%20to%2069.81%25%20when%20pulling%20%2A%2A7251ca80ff818be30de9ea6b8555ab7da113e5b6%20on%20krocard%3ADisable_fix_point_test_if_no_python_bindings%2A%2A%20into%20%2A%2A9d1bcf046870f2c3bafede70dbb86c977b93c360%20on%2001org%3Amaster%2A%2A.%5Cn%22%2C%20%22created_at%22%3A%20%222015-05-20T12%3A39%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2354108%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/coveralls%22%7D%7D%2C%20%7B%22body%22%3A%20%22fixed%20point%20tests%20have%20not%20been%20run.%20I%20guess%20that%27s%20because%20of%20the%20order%20in%20which%20the%20subdirs%20are%20parsed.%20All%20options%20should%20probably%20be%20declared%20in%20the%20main%20CMakeLists.txt.%20That%20would%20be%20a%20separate%2C%20preliminary%20fix.%22%2C%20%22created_at%22%3A%20%222015-05-20T13%3A08%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22That%20is%20unfortunate.%20Strange%20cmake%20does%20not%20complain%20about%20an%20unset%20variable%20though.%20As%20you%20said%2C%20it%20might%20be%20better%20to%20regroup%20all%20option%20in%20the%20same%20place.%22%2C%20%22created_at%22%3A%20%222015-05-20T14%3A14%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22Abandon%20as%20I%20can%20not%20see%20a%20proper%20fix.%20Opened%20a%20bug%20instead%3A%20%23163%22%2C%20%22created_at%22%3A%20%222015-08-18T16%3A08%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/116#issuecomment-103846117'>General Comment</a></b>
- <a href='https://github.com/krocard'></a> :+1: @OznOg @dawagner
- <a href='https://github.com/coveralls'></a> [Coverage Status](https://coveralls.io/builds/2606986)
Coverage decreased (-0.33%) to 69.81% when pulling **7251ca80ff818be30de9ea6b8555ab7da113e5b6 on krocard:Disable_fix_point_test_if_no_python_bindings** into **9d1bcf046870f2c3bafede70dbb86c977b93c360 on 01org:master**.
- <a href='https://github.com/dawagner'></a> fixed point tests have not been run. I guess that's because of the order in which the subdirs are parsed. All options should probably be declared in the main CMakeLists.txt. That would be a separate, preliminary fix.
- <a href='https://github.com/krocard'></a> That is unfortunate. Strange cmake does not complain about an unset variable though. As you said, it might be better to regroup all option in the same place.
- <a href='https://github.com/krocard'></a> Abandon as I can not see a proper fix. Opened a bug instead: #163

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/116?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/116?approve=1'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/116'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by krocard** [comment]
:+1: @OznOg @dawagner

**Comment by dawagner** [comment]
fixed point tests have not been run. I guess that's because of the order in which the subdirs are parsed. All options should probably be declared in the main CMakeLists.txt. That would be a separate, preliminary fix.

**Comment by krocard** [comment]
That is unfortunate. Strange cmake does not complain about an unset variable though. As you said, it might be better to regroup all option in the same place.

**Comment by krocard** [comment]
Abandon as I can not see a proper fix. Opened a bug instead: #163

**Pull request closed without merging**
