### PR TITLE
bindings/c: build fix vs clang3.6

### PR DESCRIPTION
**Pull request by miguelgaio**
clang3.6 complains about misalignment between declaration contract
and implementation.
ie. Parameter declared NONNULL as not to be tested against null in function.

Remove pointer tests if they are declared non null.

Signed-off-by: Miguel Gaio <miguel.gaio@intel.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141457229%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141467731%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141919900%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141922015%22%2C%20%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141940432%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/01org/parameter-framework/pull/241%23issuecomment-141457229%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40OznOg%20%40krocard%20%40dawagner%20%40cc6565%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-18T13%3A53%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22Please%20update%20unit%20tests%20too.%22%2C%20%22created_at%22%3A%20%222015-09-18T14%3A26%3A50Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-09-21T09%3A13%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/12096004%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/miguelgaio%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%20%22%2C%20%22created_at%22%3A%20%222015-09-21T09%3A20%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6430928%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dawagner%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%20%40OznOg%20please%20review%22%2C%20%22created_at%22%3A%20%222015-09-21T10%3A54%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/krocard%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/krocard%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/6862950%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/krocard'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/01org/parameter-framework/pull/241#issuecomment-141457229'>General Comment</a></b>
- <a href='https://github.com/miguelgaio'></a> @OznOg @krocard @dawagner @cc6565 please review
- <a href='https://github.com/krocard'></a> Please update unit tests too.
- <a href='https://github.com/miguelgaio'></a> :+1:
- <a href='https://github.com/dawagner'></a> :+1:
- <a href='https://github.com/krocard'></a> :shipit: @OznOg please review

<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/241?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/241?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/01org/parameter-framework/pull/241?approve=0'></a>&nbsp;<a href='https://github.com/01org/parameter-framework/pull/241'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by miguelgaio** [comment]
@OznOg @krocard @dawagner @cc6565 please review

**Comment by krocard** [comment]
Please update unit tests too.

**Comment by miguelgaio** [comment]
:+1:

**Comment by dawagner** [comment]
:+1:

**Comment by krocard** [comment]
:shipit: @OznOg please review

**Pull request merged**
